package com.ierdely.elective_courses.security;

public interface SecurityRoles {
    String ROLE_PREFIX = "ROLE_";

    String ADMIN = "ADMIN";
    
    String STUDENT = "STUDENT";
    
    
    String COURSES_ADMIN = "CUSTOMERS_ADMIN";
    String COURSES_CREATE = "COURSE_CREATE";
    String COURSES_READ = "COURSE_READ";
    String COURSES_UPDATE = "COURSE_UPDATE";
    String COURSES_DELETE = "COURSE_DELETE";
    String COURSES_PAG_VIEW = "COURSE_PAG_VIEW";

    String USERS_ADMIN = "USERS_ADMIN";
    String USERS_CREATE = "USERS_CREATE";
    String USERS_READ = "USERS_READ";
    String USERS_UPDATE = "USERS_UPDATE";
    String USERS_DELETE = "USERS_DELETE";
    String USERS_PAG_VIEW = "USERS_PAG_VIEW";
    
    String TEACHERS_ADMIN = "TEACHERS_ADMIN";
    String TEACHERS_CREATE = "TEACHERS_CREATE";
    String TEACHERS_READ = "TEACHERS_READ";
    String TEACHERS_UPDATE = "TEACHERS_UPDATE";
    String TEACHERS_DELETE = "TEACHERS_DELETE";
    String TEACHERS_PAG_VIEW = "TEACHERS_PAG_VIEW";
    
    String ENROLLMENTS_ADMIN = "ENROLLMENTS_ADMIN";
    String ENROLLMENTS_CREATE = "ENROLLMENTS_CREATE";
    String ENROLLMENTS_READ = "ENROLLMENTS_READ";
    String ENROLLMENTS_UPDATE = "ENROLLMENTS_UPDATE";
    String ENROLLMENTS_DELETE = "ENROLLMENTS_DELETE";
    String ENROLLMENTS_PAG_VIEW = "ENROLLMENTS_PAG_VIEW";

}
